[module]
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/images"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/basic-seo"