name = "Indigo Theme"
license = "MIT"
description = "Theme for the Webera ecosystem"
homepage = "https://webera.com/"
tags = ["blog", "company", "webera"]
features = ["blog", "Responsive"]
min_version = "0.41"

[author]
  name = "Webera"
  homepage = "https://webera.com/"
