baseURL = "https://example.com"
languageCode = "en-us"
title = "My Website"
theme = "github.com/wearewebera/indigo-theme"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
attribute = true