baseURL = "https://example.com"
disableKinds = ["page", "section", "taxonomy", "term"]
languageCode = "en-us"
title = "My Website"
theme = "github.com/wearewebera/indigo-theme"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
attribute = true

[pagination]
disableAliases = false
pagerSize = 6
path = 'page'
