[metadata]
keywords = ["Webera", "Hugo", "Theme"]
description = "This is default meta description"

[cookies]
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

[footer]
copyright = "© All rights reserved."
