[metadata]
keywords = ["Webera", "Hugo", "Tema"]
description = "Este é o meta descrição padrão"

[cookies]
content = "Este site usa cookies. Ao continuar a usar este site, você concorda com o uso deles."
button = "Eu aceito"

[footer]
copyright = "© Todos os direitos reservados."
