[[main]]
name = "Slides"
hasChildren = true
weight = 1

[[main]]
parent = "Slides"
name = "Introdução"
url = "/"
weight = 1

[[main]]
parent = "Slides"
name = "Objetivos"
url = "/slides/2"
weight = 2

[[main]]
parent = "Slides"
name = "Características"
url = "/slides/3"
weight = 3

[[main]]
parent = "Slides"
name = "Filosofia"
url = "/slides/4"
weight = 4

[[main]]
parent = "Slides"
name = "Próximos passos"
url = "/slides/5"
weight = 5

[[main]]
parent = "Slides"
name = "Cases"
url = "/slides/6"
weight = 6

[[main]]
parent = "Slides"
name = "Exemplos"
url = "/slides/7"
weight = 7

[[main]]
parent = "Slides"
name = "Conclusão"
url = "/slides/8"
weight = 8
